Repository liquibase/liquibase-hibernate, pull requests merged in 2023-11, with the labels that each got.

#555 use unique name for backing index of unique constraints
  src/main/java/liquibase/ext/hibernate/snapshot/UniqueConstraintSnapshotGenerator.java
  src/test/java/com/example/ejb3/auction/Item.java
  src/test/java/liquibase/ext/hibernate/SpringPackageScanningIntegrationTest.java
Labels: TypeBug

#616 use hibernate.temp.use_jdbc_metadata_defaults=false everywhere like for HibernateClassic
  src/main/java/liquibase/ext/hibernate/database/HibernateClassicDatabase.java
  src/main/java/liquibase/ext/hibernate/database/HibernateDatabase.java
  src/main/java/liquibase/ext/hibernate/database/HibernateEjb3Database.java
  src/main/java/liquibase/ext/hibernate/database/HibernateSpringPackageDatabase.java
  src/main/java/liquibase/ext/hibernate/database/JpaPersistenceDatabase.java
Labels: TypeEnhancement

#600 Fixed a typo in ReadMe
  README.md
Labels: TypeBug

#618 Fix trigger of builds
  .github/workflows/test.yml
Labels: skipReleaseNotes

#619 Fix tests
  src/test/java/liquibase/ext/hibernate/HibernateIntegrationTest.java
Labels: TypeBug

#622 Liquibase 4.25.0
  .github/workflows/test.yml
  pom.xml
Labels: skipReleaseNotes

#623 Liquibase 4.25.0
  .github/workflows/test.yml
  pom.xml
Labels: skipReleaseNotes

#612 test build
  pom.xml
Labels: skipReleaseNotes
