Repository liquibase/liquibase-hibernate, pull requests merged in 2024-10, with the labels that each got.

#721 fix: update filename used in badge to show nightly build status
  README.md
Labels: skipReleaseNotes

#717 Enables catalog support for HibernateDatabase so that diff-changelog generation works again
  src/main/java/liquibase/ext/hibernate/database/HibernateDatabase.java
Labels: TypeBug

#719 Removes validate differences when comparing an Oracle Database Schema against a Spring Jpa / HibernateDatabase, fixes #718
  src/main/java/liquibase/ext/hibernate/diff/ChangedForeignKeyChangeGenerator.java
  src/main/java/liquibase/ext/hibernate/diff/ChangedPrimaryKeyChangeGenerator.java
Labels: TypeEnhancement
