Repository liquibase/liquibase-hibernate, pull requests merged in 2024-03, with the labels that each got.

#665 fix: allow building forked branches
  .github/workflows/test.yml
Labels: skipReleaseNotes

#647 chore(pom.xml): Add licenses-, organization-, issueManagement- and ciManagement-sections
  pom.xml
Labels: TypeEnhancement, sdou

#664 Fixes #663: Bug on diff, TIME needs to be handled same as TIMESTAMP
  src/main/java/liquibase/ext/hibernate/diff/ChangedColumnChangeGenerator.java
Labels: TypeBug
